import type { GradeBand, UniversityId, UniversityPolicy } from "./types";

const grade = (letter: string, minPercent: number, maxPercent: number, value: number): GradeBand => ({
  letter,
  minPercent,
  maxPercent,
  value,
});

const ontarioFourPointBands = (aPlusValue = 4.0): GradeBand[] => [
  grade("A+", 90, 100, aPlusValue),
  grade("A", 85, 89.999, 4.0),
  grade("A-", 80, 84.999, 3.7),
  grade("B+", 77, 79.999, 3.3),
  grade("B", 73, 76.999, 3.0),
  grade("B-", 70, 72.999, 2.7),
  grade("C+", 67, 69.999, 2.3),
  grade("C", 63, 66.999, 2.0),
  grade("C-", 60, 62.999, 1.7),
  grade("D+", 57, 59.999, 1.3),
  grade("D", 53, 56.999, 1.0),
  grade("D-", 50, 52.999, 0.7),
  grade("F", 0, 49.999, 0.0),
];

const ontarioPercentFallbackBands = (): GradeBand[] => [
  grade("A+", 90, 100, 95),
  grade("A", 85, 89.999, 87),
  grade("A-", 80, 84.999, 82),
  grade("B+", 77, 79.999, 78),
  grade("B", 73, 76.999, 75),
  grade("B-", 70, 72.999, 71),
  grade("C+", 67, 69.999, 68),
  grade("C", 63, 66.999, 65),
  grade("C-", 60, 62.999, 61),
  grade("D+", 57, 59.999, 58),
  grade("D", 53, 56.999, 55),
  grade("D-", 50, 52.999, 51),
  grade("F", 0, 49.999, 0),
];

const tmuBands: GradeBand[] = [
  grade("A+", 90, 100, 4.33),
  grade("A", 85, 89.999, 4.0),
  grade("A-", 80, 84.999, 3.67),
  grade("B+", 77, 79.999, 3.33),
  grade("B", 73, 76.999, 3.0),
  grade("B-", 70, 72.999, 2.67),
  grade("C+", 67, 69.999, 2.33),
  grade("C", 63, 66.999, 2.0),
  grade("C-", 60, 62.999, 1.67),
  grade("D+", 57, 59.999, 1.33),
  grade("D", 53, 56.999, 1.0),
  grade("D-", 50, 52.999, 0.67),
  grade("F", 0, 49.999, 0.0),
];

const westernBands: GradeBand[] = [
  grade("A+", 90, 100, 95),
  grade("A", 80, 89.999, 84.5),
  grade("B", 70, 79.999, 74.5),
  grade("C", 60, 69.999, 64.5),
  grade("D", 50, 59.999, 54.5),
  grade("E", 40, 49.999, 45),
  grade("F", 0, 39.999, 40),
  grade("FAI", 0, 49.999, 40),
];

const yorkNinePointBands: GradeBand[] = [
  grade("A+", 90, 100, 9),
  grade("A", 80, 89.999, 8),
  grade("B+", 75, 79.999, 7),
  grade("B", 70, 74.999, 6),
  grade("C+", 65, 69.999, 5),
  grade("C", 60, 64.999, 4),
  grade("D+", 55, 59.999, 3),
  grade("D", 50, 54.999, 2),
  grade("E", 40, 49.999, 1),
  grade("F", 0, 39.999, 0),
];

const laurierBands: GradeBand[] = [
  grade("A+", 90, 100, 12),
  grade("A", 85, 89.999, 11),
  grade("A-", 80, 84.999, 10),
  grade("B+", 77, 79.999, 9),
  grade("B", 73, 76.999, 8),
  grade("B-", 70, 72.999, 7),
  grade("C+", 67, 69.999, 6),
  grade("C", 63, 66.999, 5),
  grade("C-", 60, 62.999, 4),
  grade("D+", 57, 59.999, 3),
  grade("D", 53, 56.999, 2),
  grade("D-", 50, 52.999, 1),
  grade("F", 0, 49.999, 0),
  grade("XF", 0, 49.999, 0),
  grade("DR", 0, 49.999, 0),
];

const uOttawaBands: GradeBand[] = [
  grade("A+", 90, 100, 10),
  grade("A", 85, 89.999, 9),
  grade("A-", 80, 84.999, 8),
  grade("B+", 75, 79.999, 7),
  grade("B", 70, 74.999, 6),
  grade("C+", 65, 69.999, 5),
  grade("C", 60, 64.999, 4),
  grade("D+", 55, 59.999, 3),
  grade("D", 50, 54.999, 2),
  grade("E", 40, 49.999, 1),
  grade("F", 0, 39.999, 0),
  grade("ABS", 0, 0, 0),
  grade("EIN", 0, 0, 0),
];

const mcGillBands: GradeBand[] = [
  grade("A", 85, 100, 4.0),
  grade("A-", 80, 84.999, 3.7),
  grade("B+", 75, 79.999, 3.3),
  grade("B", 70, 74.999, 3.0),
  grade("B-", 65, 69.999, 2.7),
  grade("C+", 60, 64.999, 2.3),
  grade("C", 55, 59.999, 2.0),
  grade("D", 50, 54.999, 1.0),
  grade("F", 0, 49.999, 0.0),
];

const exclude = (...codes: string[]) => Object.fromEntries(codes.map((code) => [code, "exclude" as const]));
const zero = (...codes: string[]) => Object.fromEntries(codes.map((code) => [code, "zero" as const]));
const floor = (...codes: string[]) => Object.fromEntries(codes.map((code) => [code, "floor" as const]));

export const UNIVERSITY_POLICIES: Record<UniversityId, UniversityPolicy> = {
  uoft: {
    id: "uoft",
    name: "University of Toronto",
    shortName: "UofT",
    scaleKind: "points",
    scaleLabel: "4.0 GPA",
    maxValue: 4,
    passingPercent: 50,
    defaultCreditWeight: 0.5,
    displayPrecision: 2,
    roundingMode: "normal-2",
    repeatPolicy: "include-all",
    repeatAutoDetectByCode: false,
    passFailFailureCounts: true,
    designationRules: {
      ...exclude("AEG", "CR", "NCR", "P", "PASS", "TR", "TRANSFER", "XMP", "EXT", "EXTRA", "LWD", "WDR", "DROP", "WD", "DNW", "SDF", "GWR", "IPR", "NGA", "INC"),
      ...zero("FL", "FAIL", "F", "NC%"),
    },
    gradeBands: ontarioFourPointBands(4.0),
    termAverageLabel: "SGPA",
    cumulativeAverageLabel: "CGPA",
    yearlyAverageLabel: "AGPA",
    notes: [
      "Weighted GPA = sum(grade point × credit weight) / sum(credit weights with grade points).",
      "SGPA is Fall, Winter, or Summer. AGPA is Fall/Winter. CGPA includes all applicable completed courses.",
      "CR/NCR normally does not affect GPA; if a no-credit result is officially GPA-counting it appears as NC% and counts 0.0.",
      "No university-wide undergraduate pre-conversion rounding rule is applied; use the posted final course result.",
      "Passed Pass/Fail, AEG, transfer/XMP, EXT/Extra, LWD/WDR/DNW/GWR/INC/IPR/NGA/SDF are excluded. Failed Pass/Fail may count as 0.0.",
      "Do not auto-detect repeats. UofT repeat treatment varies by campus/division and transcript notation; exclude EXT/Extra if the transcript marks it that way.",
    ],
    officialUrls: [
      "https://www.registrar.utoronto.ca/records-academics/transcripts/grading-scales-notations/",
      "https://artsci.calendar.utoronto.ca/print/pdf/node/15/debug",
      "https://ischool.calendar.utoronto.ca/rules-regulations",
    ],
  },

  tmu: {
    id: "tmu",
    name: "Toronto Metropolitan University",
    shortName: "TMU",
    scaleKind: "points",
    scaleLabel: "4.33 GPA",
    maxValue: 4.33,
    passingPercent: 50,
    defaultCreditWeight: 1,
    displayPrecision: 2,
    roundingMode: "normal-2",
    preConversionRounding: "nearest-integer",
    repeatPolicy: "latest-attempt-only",
    repeatAutoDetectByCode: true,
    passFailFailureCounts: true,
    designationRules: {
      ...exclude("AEG", "AUD", "CNC", "CHG", "CRT", "CRD", "CRV", "DEF", "EXN", "INC", "INP", "GNR", "NCR", "NSC", "PSD", "FLD"),
      ...zero("F", "F-S", "FS", "FNA"),
    },
    gradeBands: tmuBands,
    termAverageLabel: "TGPA",
    cumulativeAverageLabel: "CGPA",
    yearlyAverageLabel: "Year GPA",
    notes: [
      "Final percentage grades are rounded to the nearest integer before letter/point conversion. 49.5 rounds to 50; 49.4 stays 49.",
      "4.33 scale. GPA = sum(course weight × grade points) / sum(course weights), rounded to two decimals.",
      "One-term courses usually have weight 1.00; two-term courses usually have weight 2.00.",
      "First attempts of repeated courses are excluded; the most recent attempt counts even if lower.",
      "F-S and FNA count as zero. Listed non-graded designations are excluded.",
    ],
    officialUrls: [
      "https://www.torontomu.ca/current-students/grades-standings/gpa-calculation/",
      "https://www.torontomu.ca/senate/policies/undergraduate-course-grading-academic-program-standing-and-eligibility-to-graduate-policy-170-a/",
    ],
  },

  western: {
    id: "western",
    name: "Western University",
    shortName: "Western",
    scaleKind: "percent",
    scaleLabel: "Weighted average %",
    maxValue: 100,
    passingPercent: 50,
    defaultCreditWeight: 0.5,
    displayPrecision: 2,
    roundingMode: "normal-2",
    repeatPolicy: "latest-attempt-only",
    repeatAutoDetectByCode: true,
    percentFloorForAverage: 40,
    passFailFailureCounts: true,
    designationRules: {
      ...exclude("P", "PASS", "PAS", "PAS+", "CR", "AUD", "WD", "WDN", "W", "INC", "IPR", "TR", "TRANSFER", "XMP"),
      ...floor("F", "FAIL", "FAI"),
    },
    gradeBands: westernBands,
    termAverageLabel: "Term average",
    cumulativeAverageLabel: "Cumulative average",
    yearlyAverageLabel: "Year average",
    notes: [
      "Western does not issue a GPA; it uses numeric grades and weighted percentage averages.",
      "Failures are included. Numeric marks below 40 are calculated as 40; 40–49 use the actual grade.",
      "A late drop with academic penalty is recorded as F and calculated as 40.",
      "Correction from the earlier kit: repeated courses should not be include-all. All but the most recent attempt are excluded from cumulative average calculations for progression.",
    ],
    officialUrls: [
      "https://registrar.uwo.ca/services/transcripts.html",
      "https://www.westerncalendar.uwo.ca/Pages.cfm?ArchiveID=&PageID=2&SelectedCalendar=Live",
    ],
  },

  queens: {
    id: "queens",
    name: "Queen's University",
    shortName: "Queen's",
    scaleKind: "points",
    scaleLabel: "4.3 GPA",
    maxValue: 4.3,
    passingPercent: 50,
    defaultCreditWeight: 3,
    displayPrecision: 2,
    roundingMode: "normal-2",
    repeatPolicy: "best-attempt-only",
    repeatAutoDetectByCode: true,
    passFailFailureCounts: true,
    designationRules: {
      ...exclude("P", "PASS", "CR", "NG", "DR", "TR", "AU", "AUD", "GD", "IN", "INC", "IPR"),
      ...zero("F", "FAIL", "NW", "FR"),
    },
    gradeBands: ontarioFourPointBands(4.3),
    termAverageLabel: "Term GPA",
    cumulativeAverageLabel: "Cumulative GPA",
    yearlyAverageLabel: "Academic Year GPA",
    notes: [
      "GPA = total grade points divided by total GPA units.",
      "Term GPA, Academic Year GPA, Plan GPA, and Cumulative GPA exist; academic year normally includes Fall, Winter, and Summer.",
      "If a course is repeated, only the highest grade-bearing attempt is used. The lower attempt is excluded from GPA.",
      "Non-evaluative grades such as NG, CR, DR, P and transfer TR are excluded. Failed attempts are included unless replaced by a higher repeat.",
    ],
    officialUrls: [
      "https://www.queensu.ca/artsci/undergraduate/current-students/gpa-info",
      "https://www.queensu.ca/academic-calendar/arts-science/academic-regulations/",
    ],
  },

  guelph: {
    id: "guelph",
    name: "University of Guelph",
    shortName: "Guelph",
    scaleKind: "percent",
    scaleLabel: "Weighted average %",
    maxValue: 100,
    passingPercent: 50,
    defaultCreditWeight: 0.5,
    displayPrecision: 2,
    roundingMode: "normal-2",
    repeatPolicy: "include-all",
    repeatAutoDetectByCode: false,
    cumulativeRepeatPolicy: "best-attempt-only",
    cumulativeRepeatAutoDetectByCode: true,
    cumulativeRepeatEffectiveFrom: "2026-05-01",
    passFailFailureCounts: false,
    designationRules: {
      ...exclude("AUD", "AU", "CR", "CRD", "CR/NCR", "NCR", "DEF", "DFR", "INC", "INP", "MNR", "OP", "P", "PASS", "F", "WF", "XXF", "XXP", "TR", "TRANSFER", "LOP"),
    },
    gradeBands: ontarioPercentFallbackBands(),
    termAverageLabel: "Semester average",
    cumulativeAverageLabel: "Cumulative average",
    yearlyAverageLabel: "Academic year average",
    notes: [
      "Guelph uses weighted percentage averages, not a GPA scale.",
      "Use numeric final percentages whenever possible. Passed, failed, and repeated numeric course grades are used in cumulative/semester averages.",
      "Credit/No Credit courses are excluded from cumulative, semester, and specialization averages.",
      "Summer 2026 onward: repeated attempts still count in the semester average, but only the highest grade counts in the cumulative average. Earlier attempts are not treated retroactively without a completed date showing the newer rule applies.",
      "Correction from the earlier kit: do NOT silently count transcript symbols F, WF, or XXF as zero. Guelph's continuation notes say alternative evaluations like P/OP/F/CRD/WF are not included; if the student has an actual numeric failing mark, enter that percent instead.",
    ],
    officialUrls: [
      "https://calendar.uoguelph.ca/undergraduate-calendar/undergraduate-degree-regulations-procedures/grades/",
      "https://www.uoguelph.ca/registrar/enrolment-records/continuation-of-study/",
      "https://calendar.uoguelph.ca/associate-diploma/associate-diploma-regulations-procedures/credit-no-credit-grading-option/",
    ],
  },

  brock: {
    id: "brock",
    name: "Brock University",
    shortName: "Brock",
    scaleKind: "percent",
    scaleLabel: "Weighted average %",
    maxValue: 100,
    passingPercent: 50,
    defaultCreditWeight: 0.5,
    displayPrecision: 0,
    roundingMode: "normal-0",
    repeatPolicy: "latest-attempt-only",
    repeatAutoDetectByCode: true,
    percentFloorForAverage: 45,
    passFailFailureCounts: true,
    designationRules: {
      ...exclude("CH", "CD", "ND", "WDD", "AUD", "IN", "INC", "IP", "IPR", "NR", "NW", "H", "P", "PASS", "CR", "TR", "TRANSFER", "LOP", "AG", "AEG"),
      ...floor("F", "FAIL"),
    },
    gradeBands: [
      grade("A", 80, 100, 90),
      grade("B", 70, 79.999, 75),
      grade("C", 60, 69.999, 65),
      grade("D", 50, 59.999, 55),
      grade("F", 0, 49.999, 45),
    ],
    termAverageLabel: "Term average",
    cumulativeAverageLabel: "Cumulative average",
    yearlyAverageLabel: "Year average",
    notes: [
      "Brock average = sum(credit weight × numeric grade) / credits attempted.",
      "Averages are rounded to the nearest whole percent.",
      "Grades below 45 are calculated as 45. F grades of 46–49 use the actual numeric value.",
      "If a course is retaken, only the later attempt is counted, whether higher or lower.",
    ],
    officialUrls: [
      "https://brocku.ca/academic-advising/student-resources/",
      "https://brocku.ca/university-secretariat/faculty-handbook/section-3/",
    ],
  },

  york: {
    id: "york",
    name: "York University",
    shortName: "York",
    scaleKind: "points",
    scaleLabel: "9.0 GPA",
    maxValue: 9,
    passingPercent: 50,
    defaultCreditWeight: 3,
    displayPrecision: 2,
    roundingMode: "normal-2",
    repeatPolicy: "latest-attempt-only",
    repeatAutoDetectByCode: true,
    passFailFailureCounts: false,
    designationRules: {
      ...exclude("P", "PASS", "CR", "NCR", "W", "WD", "AUD", "TR", "TRANSFER", "INC", "DEF", "NG", "UNSUPPORTED"),
      ...zero("F"),
    },
    gradeBands: yorkNinePointBands,
    termAverageLabel: "Sessional GPA",
    cumulativeAverageLabel: "Cumulative GPA",
    yearlyAverageLabel: "Academic year GPA",
    notes: [
      "York uses a 9-point GPA. GPA is credit-weighted from letter grade point value × credit value.",
      "Only the most recent completed attempt of a repeated course counts toward GPA and credit totals.",
      "Unsupported/non-GPA courses should be excluded.",
      "Pass/Fail option courses should not affect GPA. This is why passFailFailureCounts is false even though ordinary letter F is 0.",
      "Percent ranges are guidelines; York's official system is letter-grade based.",
    ],
    officialUrls: [
      "https://students.yorku.ca/york-gpa-calculator",
      "https://calendars.students.yorku.ca/2024-2025/grades-and-grading-schemes",
      "https://myacademicrecord.students.yorku.ca/course-repeat",
    ],
  },

  waterloo: {
    id: "waterloo",
    name: "University of Waterloo",
    shortName: "Waterloo",
    scaleKind: "percent",
    scaleLabel: "Weighted average %",
    maxValue: 100,
    passingPercent: 50,
    defaultCreditWeight: 0.5,
    displayPrecision: 3,
    roundingMode: "truncate-3",
    repeatPolicy: "manual-review",
    repeatAutoDetectByCode: false,
    percentFloorForAverage: 32,
    passFailFailureCounts: false,
    designationRules: {
      ...exclude("AEG", "AUD", "CR", "NCR", "INC", "IPR", "MM", "WD", "W", "P", "PASS", "TR", "TRANSFER", "LOP"),
      ...floor("F", "FTC", "NMR", "DNW", "WF"),
    },
    gradeBands: [
      grade("A+", 90, 100, 95),
      grade("A", 85, 89.999, 89),
      grade("A-", 80, 84.999, 83),
      grade("B+", 77, 79.999, 78),
      grade("B", 73, 76.999, 75),
      grade("B-", 70, 72.999, 72),
      grade("C+", 67, 69.999, 68),
      grade("C", 63, 66.999, 65),
      grade("C-", 60, 62.999, 62),
      grade("D+", 57, 59.999, 58),
      grade("D", 53, 56.999, 55),
      grade("D-", 50, 52.999, 52),
      grade("F+", 42, 49.999, 46),
      grade("F", 35, 41.999, 38),
      grade("F-", 0, 34.999, 32),
    ],
    termAverageLabel: "Term average",
    cumulativeAverageLabel: "Cumulative average",
    yearlyAverageLabel: "Year average",
    notes: [
      "Waterloo uses numeric percentage grades and credit-weighted percentage averages.",
      "Any grade between 0 and 32 is treated as 32 when averages are calculated for promotions/awards.",
      "CR is credit granted but not included in averages. FTC, NMR, DNW, and WF calculate as 32.",
      "Correction/edge case: repeat-course treatment is faculty/plan-specific, so the engine should not automatically remove repeated Waterloo attempts. Keep all grade-bearing attempts unless the user/transcript/faculty rule says otherwise, and show a warning when repeatGroupId is present.",
    ],
    officialUrls: [
      "https://academic-calendar-archive.uwaterloo.ca/undergraduate-studies/2023-2024/page/Acad-Regs-Grades.html",
      "https://uwaterloo.ca/math/understanding-your-unofficial-transcript",
      "https://uwaterloo.ca/engineering/undergraduate-students/first-year/your-academic-student-record",
      "https://academic-calendar-archive.uwaterloo.ca/undergraduate-studies/2023-2024/page/SCI-Repeating-and-Counting-of-Courses.html",
    ],
  },

  laurier: {
    id: "laurier",
    name: "Wilfrid Laurier University",
    shortName: "Laurier",
    scaleKind: "points",
    scaleLabel: "12-point GPA",
    maxValue: 12,
    passingPercent: 50,
    defaultCreditWeight: 0.5,
    displayPrecision: 2,
    roundingMode: "normal-2",
    repeatPolicy: "latest-attempt-only",
    repeatAutoDetectByCode: true,
    passFailFailureCounts: true,
    designationRules: {
      ...exclude("P", "PASS", "S", "SAT", "U", "UNSAT", "UR", "GNR", "WD", "AUD", "CR", "TR", "TRANSFER", "INC", "IPR"),
      ...zero("F", "XF", "DR"),
    },
    gradeBands: laurierBands,
    termAverageLabel: "Term GPA",
    cumulativeAverageLabel: "Cumulative GPA",
    yearlyAverageLabel: "Year GPA",
    notes: [
      "Laurier uses a 12-point GPA scale. GPA = weighted grade points / credits attempted.",
      "GPA is rounded to two decimal places.",
      "For repeats, the second/later attempt is used in GPA even if lower; the first attempt remains on transcript but is not used.",
      "Failed courses DR, XF, and F are zero GPA values. WD and CR credits are excluded from GPA credit totals.",
    ],
    officialUrls: [
      "https://students.wlu.ca/academics/support-and-advising/gpa-calculator/index.html",
      "https://academic-calendar.wlu.ca/section.php?cal=1&s=1156&sp=3826&ss=4581&y=92",
      "https://academic-calendar.wlu.ca/glossary.php?cal=1&g=1484&y=90",
    ],
  },

  uottawa: {
    id: "uottawa",
    name: "University of Ottawa",
    shortName: "uOttawa",
    scaleKind: "points",
    scaleLabel: "10-point CGPA",
    maxValue: 10,
    passingPercent: 50,
    defaultCreditWeight: 3,
    displayPrecision: 2,
    roundingMode: "normal-2",
    preConversionRounding: "nearest-integer",
    repeatPolicy: "latest-attempt-only",
    repeatAutoDetectByCode: true,
    passFailFailureCounts: false,
    designationRules: {
      ...exclude("AUD", "CR", "NC", "P", "S", "NS", "DR", "DFR", "CTN", "NNR", "Q", "TR", "TRANSFER", "INC", "IPR"),
      ...zero("F", "ABS", "EIN"),
    },
    gradeBands: uOttawaBands,
    termAverageLabel: "TGPA",
    cumulativeAverageLabel: "CGPA",
    yearlyAverageLabel: "Year CGPA",
    notes: [
      "uOttawa uses a 10-point alphanumeric scale.",
      "Final course percentages are rounded to the nearest integer before grade-point conversion.",
      "Grade points = course units × numeric value. TGPA/CGPA = grade points divided by units.",
      "CGPA is rounded to two decimals. CR, NC, P, S, and NS do not affect averages; ABS and EIN are equivalent to F/0.",
      "Current repeat rule: only the last grade counts in CGPA; a failing grade can replace a passing grade. Some programs are exceptions, so allow manual overrides.",
    ],
    officialUrls: [
      "https://www.uottawa.ca/about-us/leadership-governance/policies-regulations/a-3-grading-system",
      "https://www.uottawa.ca/about-us/policies-regulations/academic-regulations/b-4-registration",
    ],
  },

  mcgill: {
    id: "mcgill",
    name: "McGill University",
    shortName: "McGill",
    scaleKind: "points",
    scaleLabel: "4.0 GPA",
    maxValue: 4,
    passingPercent: 50,
    defaultCreditWeight: 3,
    displayPrecision: 2,
    roundingMode: "truncate-2",
    repeatPolicy: "include-all",
    repeatAutoDetectByCode: false,
    passFailFailureCounts: true,
    designationRules: {
      ...exclude("P", "PASS", "S", "U", "W", "WF", "WL", "KK", "KE", "K*", "K", "L", "LE", "L*", "NA", "NR", "TR", "TRANSFER", "INC", "IPR"),
      ...zero("F", "J", "KF"),
    },
    gradeBands: mcGillBands,
    termAverageLabel: "TGPA",
    cumulativeAverageLabel: "CGPA",
    yearlyAverageLabel: "Year GPA",
    notes: [
      "McGill uses a 4.0 scale with no A+ grade point above 4.0.",
      "GPA = sum(course credit × grade points) / sum(GPA course credits). GPA display is not rounded up; truncate display to two decimals.",
      "D and F remain in CGPA even after retaking the course; all repeated final grades are included, but credit is granted only once.",
      "S/U grades are excluded from GPA, including U. J and KF count as failures/0; W/WF/WL/KK and incomplete/deferred-style symbols are excluded until resolved.",
    ],
    officialUrls: [
      "https://coursecatalogue.mcgill.ca/en/regulations/undergraduate/student-records/grading-gpa/",
      "https://www.mcgill.ca/students/courses/plan/s-u",
    ],
  },
};

export const UNIVERSITY_IDS = Object.keys(UNIVERSITY_POLICIES) as UniversityId[];

export function getUniversityPolicy(universityId: UniversityId): UniversityPolicy {
  return UNIVERSITY_POLICIES[universityId];
}
